name = "Pyonpack"
author = "masuteri"
version = "0.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58aed678c42671d3da3ff1ef57d18545f2d231696cbefa70881e3a62585c38db"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
