name = "Pyonpack"
author = "masuteri"
version = "0.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab8120a008ec41bb13eedaec0a9498dab56fce9d13b8118a98a180e672b77af"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
