name = "Pyonpack"
author = "masuteri"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a8cfb8b76a5304ba11e3fc1fad63e0a669479801a9d7df4b6654823cb6b47f9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
