name = "Pyonpack"
author = "masuteri"
version = "0.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e63f81a065462f7b5cbf6288c8ed3157e73a0b411ecd768d241e9fd91b88e7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
