name = "Pyonpack"
author = "masuteri"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "675ec44a7cddf1364dc44abda1a10b966ad65a81ce8248814408c0d289759f41"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
