name = "Pyonpack"
author = "masuteri"
version = "0.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2459c996b1f0465d488325cdcaeb499a3955438b4f654c710cd4c6c0f983bd81"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
