name = "Pyonpack"
author = "masuteri"
version = "0.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfc702cf504318d4f481404472e8d2be8f25adb0c5b698c01ff3922d6e51a3f2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
