name = "Pyonpack"
author = "masuteri"
version = "0.4.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4642036f8973abeebf6d9511296900b4d54a15d76a616e393141bbb51d85bd65"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
