name = "Pyonpack"
author = "masuteri"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01490a299832a6b96e6f0a845ebe868f3b076a504da91ab382eda8386513417f"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
